name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci  # Use npm ci for consistent builds based on package-lock.json

      - name: Transpile TypeScript to JavaScript
        run: npm run build  # Ensure you have a build script in your package.json

      - name: Zip function code WITH node_modules
        run: |
          # Navigate to the dist directory where transpiled code is located
          cd dist  # Adjust if your output directory is different
          zip -r ../lambda.zip . ../node_modules ../package.json -x "*.git*"  # Zip the contents including node_modules

      - name: Update Lambda function code
        run: aws lambda update-function-code --function-name latest-inkhub-backend --zip-file fileb://lambda.zip
